version: "3"

services:
  valheim:
    image: lloesche/valheim-server
    volumes:
      - ./config:/config
      - ./data:/opt/valheim
    ports:
      - "2456-2457:2456-2457/udp"
    cap_add:
      - SYS_NICE
    environment:
      SERVER_NAME: "DzencotWorld"
      WORLD_NAME: New11
      SERVER_PASS: dzencot
      SERVER_PUBLIC: "false"
    restart: always
    stop_grace_period: 2m
