---
- name: Setup required packages
  hosts: gameservers
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Setup required packages
      apt:
        name:
          - git
          - make
        state: present

    - name: setup pip
      include_role:
        name: geerlingguy.pip


- name: Copy worlds
  hosts: gameservers
  tasks:
    - name: Checkout repo
      ansible.builtin.git:
        repo: https://github.com/fey/valheim-server.git
        dest: /root/valheim-server

    - name: Synchronization without any --archive options enabled
      ansible.posix.synchronize:
        src: worlds/
        dest: /root/valheim-server/config/worlds

- name: deploy server
  hosts: gameservers
  tasks:
    - name: Create and start services
      community.docker.docker_compose:
        project_src: /root/valheim-server
