name: Backup Valheim worlds

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: backup_worlds.yml
          key: ${{secrets.SSH_PRIVATE_KEY}}
          # requirements: requirements.yml
          options: |
            --inventory inventory.ini

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: backup.zip
          path: |
            config/backups
